### ISSUE TITLE
does not compile on buster with node.js 13.3.0 and node-red 1.0.3

### ISSUE THREAD

**Issue by VogelP** [ludiazv/node-red-contrib-bme280#2] opened 2019-12-07 17:21 UTC
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/bme280-sensor/node_modules/i2c-bus
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i2c-bus@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the i2c-bus@1.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2019-12-07T17_12_40_774Z-debug.log](https://github.com/ludiazv/node-red-contrib-bme280/files/3935352/2019-12-07T17_12_40_774Z-debug.log)

**Comment by ludiazv** [comment] 2019-12-08 18:01
Hi,
 The problem is on the module bme280-sensor. See this issue and the fix here: https://github.com/skylarstein/bme280-sensor/issues/8.


If you can ask in the former issue for the fix maybe helps.

**Comment by nrbrt** [comment] 2019-12-15 05:41
I have forked the bme280-sensor module and corrected the i2c-bus version dependency. For a quick fix, you could change your dependency of the bme280-sensor to [my fork](https://github.com/nrbrt/bme280-sensor) and change back when the original gets updated. I also created a PR, by the way.

**Comment by nrbrt** [comment] 2019-12-16 05:44
The dependency issue has been fixed in the bme280-sensor module.

**Comment by ludiazv** [comment] 2019-12-16 09:16
Merged and updated. I Published also to npm repository.

**Closed as completed by ludiazv** 2019-12-16 09:16 UTC
Labels: bug
