### ISSUE TITLE
Address validation error

### ISSUE THREAD

**Issue by keukenrol** [ludiazv/node-red-contrib-bme280#11] opened 2022-10-18 20:30 UTC
Hi

the BME280 shows me an address validation error. NaN is not defined, despite the number being filled (0x76).

Any idea? Tried deleting the node and putting in a new one, but the issue persists.

**Comment by maga-1** [comment] 2022-11-12 19:16
This is probably the same error I have fixed in this pull request: #10

**Comment by keukenrol** [comment] 2022-11-23 07:58
Ok thanks, will this new fixed version be released via npm?

**Comment by ludiazv** [comment] 2022-11-23 08:17
Yes I try to publish it during this week.

**Comment by keukenrol** [comment] 2022-11-28 14:18
Updated today. 
Now showing error: Invalid properties: Invalid number 
-> when sea pressure is not filled in
Rest works OK!

**Comment by SirReal-surreal** [comment] 2023-02-22 07:36
Hi!
I updated to the latest node.js version (from 12 to 18) and got the same issue. As this error don't stop the code, it is still working.
However, the issue is the NaN vs. Nan typo which is fixed on 1.1.0, right? However, npm doesn't update my node to 1.1.0, it stays on 1.0.0.
I did manually edit the HTML to correct the code and it works well, now. But there is an issue with updating the node via npm.

**Comment by hasenradball** [comment] 2023-05-30 15:40
@SirReal-surreal 
Hi I have the same error....
What do I need to do?
how can I get the v 1.1.0?

**Comment by SirReal-surreal** [comment] 2023-05-31 16:09
> @SirReal-surreal Hi I have the same error.... What do I need to do? how can I get the v 1.1.0?

The update didn't work - so I edited the HTML source manually. You need to find the HTML source for the node BME280 on your raspberry and you change the "n" to a capital "N" and that's it. 

The path is something like this (if default is used):
/home/pi/.node-red/node_modules/node-red-contrib-bme280
and the file is called:
bme280.html
Line 38 (in my case).

**Comment by hasenradball** [comment] 2023-05-31 17:20
Ah for the `NAN`....

understood Thank you!

**Comment by hasenradball** [comment] 2023-05-31 19:38
But I would say if the update doesn‘ t work is a big problem.

**Comment by ludiazv** [comment] 2023-06-01 08:17
Hi guys,
   This issue is quite strange. The fix for the typo in was merged in this PR #10. And the version was published to npmjs check it out: https://www.npmjs.com/package/node-red-contrib-bme280

I just checked the package installing it from npm and the NaN issue is fixed. I doubt it the problem has any relation with the node version or npm as isNaN is std javascript function. So something fishy is going on.

I'm will be busy for the next  two week. So I can't do proper test. If someone is able to test why this happening pleas let me know.

**Comment by SirReal-surreal** [comment] 2023-06-01 14:43
Hi @ludiazv !
On my YouTube channel I got several guys facing this problem. All fixed it manually by changing the HTML on their own.
So, yes, it seems to be fixed in 1.1.0 but this update is not taken by npm. Not sure why, but somehow the released version is not seen as an update.
As this bug was not seen before on the older node.js versions, I can only assume that we all used 1.0.0 since a while but the older node.js version didn't complain about a missing capital N.

**Comment by hasenradball** [comment] 2023-06-01 15:07
@ludiazv 
@SirReal-surreal 
Please look to this Ticket answer I created:
[https://github.com/node-red/node-red/issues/4210#issuecomment-1572186642](https://github.com/node-red/node-red/issues/4210#issuecomment-1572186642)

Problem should be solved.

```
This is because the author of the module never requested its entry on the Flow Library to be updated to the latest version.

When logged into the Flow Library there is a 'check for updates' button in the sidebar of every page. I have just clicked that button and the entry has been updated to the latest release.

The Palette Manager catalog will be updated by an automated process in the next hour.
```

**Comment by keukenrol** [comment] 2023-06-01 15:12
Solved over here with updater using palette.

**Comment by SirReal-surreal** [comment] 2023-06-01 15:33
Great - I can see the update now:
![image](https://github.com/ludiazv/node-red-contrib-bme280/assets/76752339/92759b24-01d0-42bb-b9e5-a598d27afa98)

**Comment by hasenradball** [comment] 2023-06-01 18:51
Then I Think we can close this issue now.

**Comment by ludiazv** [comment] 2023-06-02 07:10
Thanks @hasenradball for solving the issue.

**Closed as completed by ludiazv** 2023-06-02 07:10 UTC

**Comment by hasenradball** [comment] 2023-06-02 07:36
you are welcome
😊
